INSERT INTO ExamPreparation (category, sub_category, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
("JEE Mains", "Easy", "What is the SI unit of force?", "Joule", "Newton", "Pascal", "Watt", "B"),
("JEE Mains", "Easy", "A car moving with a velocity of 10 m/s comes to rest in 5 seconds. What is its acceleration?", "2 m/s²", "-2 m/s²", "0 m/s²", "10 m/s²", "B"),
("JEE Mains", "Easy", "Which of the following is a scalar quantity?", "Velocity", "Acceleration", "Work", "Displacement", "C"),
("JEE Mains", "Easy", "A ball is thrown vertically upwards with a velocity of 20 m/s. What is its maximum height?", "10 m", "20 m", "30 m", "20.4 m", "D"),
("JEE Mains", "Easy", "The energy stored in a stretched spring is called:", "Kinetic Energy", "Potential Energy", "Elastic Potential Energy", "Thermal Energy", "C"),
("JEE Mains", "Easy", "The atomic number of oxygen is:", "6", "7", "8", "9", "C"),
("JEE Mains", "Easy", "Which of the following is a noble gas?", "Oxygen", "Hydrogen", "Helium", "Nitrogen", "C"),
("JEE Mains", "Easy", "What is the chemical formula of washing soda?", "NaHCO₃", "Na₂CO₃", "NaOH", "CaCO₃", "B"),
("JEE Mains", "Easy", "The pH of pure water is:", "5", "6", "7", "8", "C"),
("JEE Mains", "Easy", "The value of sin 90° is:", "0", "1", "-1", "√3/2", "B"),
("JEE Mains", "Easy", "What is the acceleration due to gravity on the Moon?", "9.8 m/s²", "1.62 m/s²", "3.7 m/s²", "5.8 m/s²", "B"),
("JEE Mains", "Easy", "Which of the following is NOT a unit of energy?", "Joule", "Erg", "Watt", "Calorie", "C"),
("JEE Mains", "Easy", "If the focal length of a convex lens is 20 cm, what is its power?", "2D", "5D", "10D", "20D", "B"),
("JEE Mains", "Easy", "What is the hybridization of Carbon in CH₄?", "sp", "sp²", "sp³", "sp³d", "C"),
("JEE Mains", "Easy", "Which metal reacts with water to produce hydrogen gas?", "Gold", "Sodium", "Copper", "Silver", "B"),
("JEE Mains", "Easy", "What is the integral of x²?", "x³/3", "x²", "x³/2", "x", "A"),
("JEE Mains", "Easy", "The equation x² - 5x + 6 = 0 has roots:", "2, 3", "-2, -3", "1, 6", "3, 5", "A"),
("JEE Mains", "Easy", "What is the escape velocity from Earth?", "9.8 km/s", "11.2 km/s", "7.9 km/s", "5.2 km/s", "B"),
("JEE Mains", "Easy", "The total number of valence electrons in CO₂ is:", "12", "16", "20", "24", "B"),
("JEE Mains", "Easy", "If a matrix A is of order 3×3, how many elements does it contain?", "6", "9", "12", "3", "B"),
('JEE Mains', 'Easy', 'The cube of 3 is:', '6', '9', '27', '81', '27'),
('JEE Mains', 'Easy', 'The value of π (pi) is approximately:', '2.14', '3.14', '4.14', '5.14', '3.14'),
('JEE Mains', 'Easy', 'What is the value of log 1 to any base?', '0', '1', '-1', 'Undefined', '0'),
('JEE Mains', 'Easy', 'What is the chemical formula of ammonia?', 'NH₄', 'NH₃', 'NO₂', 'NO₃', 'NH₃'),
('JEE Mains', 'Easy', 'If a number is divisible by 2 and 3, it is also divisible by:', '5', '6', '7', '8', '6');

INSERT INTO ExamPreparation (category, sub_category, question, option_A, option_B, option_C, option_D, correct_answer)
VALUES
('JEE Mains', 'Medium', 'A block of mass m is moving with velocity v. Its momentum is given by:', 'mv²', 'mv', '½ mv²', 'mv³', 'mv'),
('JEE Mains', 'Medium', 'A car is moving in a circular path with uniform speed. Which quantity remains constant?', 'Velocity', 'Acceleration', 'Speed', 'None', 'Speed'),
('JEE Mains', 'Medium', 'The unit of magnetic flux is:', 'Tesla', 'Weber', 'Henry', 'Farad', 'Weber'),
('JEE Mains', 'Medium', 'The force acting between two point charges q₁ and q₂ separated by distance r is given by:', 'F = kq₁q₂/r', 'F = kq₁q₂/r²', 'F = kq₁q₂r', 'F = kq₁q₂/r³', 'F = kq₁q₂/r²'),
('JEE Mains', 'Medium', 'A capacitor stores energy in the form of:', 'Magnetic field', 'Electric field', 'Kinetic energy', 'Thermal energy', 'Electric field'),
('JEE Mains', 'Medium', 'The dimensional formula of work done is:', 'ML²T⁻²', 'MLT⁻²', 'ML²T⁻³', 'MLT⁻³', 'ML²T⁻²'),
('JEE Mains', 'Medium', 'The sum of oxidation states of all atoms in a neutral compound is:', '-1', '1', '0', '2', '0'),
('JEE Mains', 'Medium', 'The gas that follows the ideal gas equation at all conditions is:', 'Oxygen', 'Hydrogen', 'Nitrogen', 'None', 'Hydrogen'),
('JEE Mains', 'Medium', 'The total number of atoms in one molecule of Ca₃(PO₄)₂ is:', '5', '8', '13', '10', '13'),
('JEE Mains', 'Medium', 'The molecular formula of quicklime is:', 'CaO', 'Ca(OH)₂', 'CaCO₃', 'CaH₂', 'CaO'),
('JEE Mains', 'Medium', 'The function f(x) = |x| is:', 'Differentiable everywhere', 'Continuous but not differentiable at x = 0', 'Discontinuous', 'Differentiable everywhere except x = 1', 'Continuous but not differentiable at x = 0'),
('JEE Mains', 'Medium', 'The integration of ∫ e^x dx is:', 'e^x + C', 'x e^x', 'ln x', 'None', 'e^x + C'),
('JEE Mains', 'Medium', 'If sin²θ + cos²θ = ?', '0', '1', '2', '-1', '1'),
('JEE Mains', 'Medium', 'The solution of dy/dx = x² is:', 'y = x³/3 + C', 'y = 3x²', 'y = e^x', 'None', 'y = x³/3 + C'),
('JEE Mains', 'Medium', 'The area of a triangle with vertices (0, 0), (a, 0), and (0, b) is:', '½ ab', 'ab', '2ab', '¼ ab', '½ ab'),
('JEE Mains', 'Medium', 'The determinant of a diagonal matrix is:', 'Always 0', 'Product of diagonal elements', 'Sum of diagonal elements', 'None', 'Product of diagonal elements'),
('JEE Mains', 'Medium', 'The period of y = sin 2x is:', 'π', '2π', 'π/2', '4π', 'π'),
('JEE Mains', 'Medium', 'If x² + y² = 25, then dy/dx is:', '-x/y', '-y/x', 'x/y', 'y/x', '-x/y'),
('JEE Mains', 'Medium', 'The derivative of log x with respect to x is:', '1/x', 'x log x', 'x log e', 'e^x', '1/x'),
('JEE Mains', 'Medium', 'The function f(x) = x³ - 3x² + 2x has local minima at:', 'x = 2', 'x = 1', 'x = 0', 'None', 'x = 2'),
('JEE Mains', 'Medium', 'The focal length of a convex mirror is always:', 'Positive', 'Negative', 'Zero', 'None', 'Negative'),
('JEE Mains', 'Medium', 'The energy of a photon is given by:', 'E = hν', 'E = mc²', 'E = h/λ', 'None', 'E = hν'),
('JEE Mains', 'Medium', 'The heat required to raise the temperature of 1g of water by 1°C is:', '1 Joule', '1 Calorie', '1 Watt', '1 Henry', '1 Calorie'),
('JEE Mains', 'Medium', 'If x⁴ - 2x² + 1 = 0, then x = ?', '±1', '±2', '±3', 'None', '±1'),
('JEE Mains', 'Medium', 'The sum of infinite terms in a GP with first term a and common ratio r < 1 is:', 'a / (1 - r)', 'a(1 - r)', 'a / (1 + r)', 'None', 'a / (1 - r)');

select * from ExamPreparation where category = 'JEE Mains';

INSERT INTO ExamPreparation (category, sub_category, question, option_A, option_B, option_C, option_D, correct_answer)
VALUES
('JEE Mains', 'Hard', 'The moment of inertia of a solid sphere about its diameter is:', '2/5 MR²', '1/2 MR²', '2/3 MR²', 'MR²', '2/5 MR²'),
('JEE Mains', 'Hard', 'A projectile is fired with an initial speed u at an angle θ. The maximum range occurs at:', '30°', '45°', '60°', '90°', '45°'),
('JEE Mains', 'Hard', 'The escape velocity from Earth is approximately:', '9.8 km/s', '11.2 km/s', '7.9 km/s', '5.2 km/s', '11.2 km/s'),
('JEE Mains', 'Hard', 'A particle moves in a circular path with constant speed. Which of the following is true?', 'Only kinetic energy changes', 'Only velocity changes', 'Acceleration is zero', 'Both velocity and acceleration change', 'Both velocity and acceleration change'),
('JEE Mains', 'Hard', 'The bond order of oxygen molecule (O₂) is:', '1', '2', '3', '2.5', '2'),
('JEE Mains', 'Hard', 'The standard Gibbs free energy change for a reaction is negative. This implies that the reaction:', 'is non-spontaneous', 'occurs at equilibrium', 'is spontaneous', 'has a positive entropy change', 'is spontaneous'),
('JEE Mains', 'Hard', 'The solubility of AgCl is least in:', 'Pure water', '0.1 M NaCl', '0.1 M NH₄Cl', '0.1 M HCl', '0.1 M NaCl'),
('JEE Mains', 'Hard', 'What is the oxidation state of Fe in Fe(CO)₅?', '+1', '+2', '0', '-1', '0'),
('JEE Mains', 'Hard', 'The half-life of a radioactive substance is T. What fraction remains after 3T?', '1/2', '1/4', '1/8', '1/16', '1/8'),
('JEE Mains', 'Hard', 'If a particle of mass m is moving at speed v, its de Broglie wavelength is:', 'h/mv', 'mv/h', 'hv/m', 'h/vm', 'h/mv'),
('JEE Mains', 'Hard', 'The energy of an electron in the first Bohr orbit of a hydrogen atom is -13.6 eV. What is its energy in the second orbit?', '-6.8 eV', '-3.4 eV', '-1.7 eV', '0 eV', '-3.4 eV'),
('JEE Mains', 'Hard', 'The value of lim (x→0) (sin x/x) is:', '0', '1', '-1', '∞', '1'),
('JEE Mains', 'Hard', 'The solution of dy/dx = e^x is:', 'y = e^x + C', 'y = e^x', 'y = x e^x', 'None of these', 'y = e^x + C'),
('JEE Mains', 'Hard', 'The integral ∫x ln x dx is solved using:', 'Substitution', 'By parts', 'Partial fractions', 'Direct integration', 'By parts'),
('JEE Mains', 'Hard', 'The determinant of the matrix [[1,2],[3,4]] is:', '-2', '-4', '-2', '2', '-2'),
('JEE Mains', 'Hard', 'The differential equation for simple harmonic motion is:', 'd²x/dt² + x = 0', 'd²x/dt² - x = 0', 'd²x/dt² + ω²x = 0', 'd²x/dt² - ω²x = 0', 'd²x/dt² + ω²x = 0'),
('JEE Mains', 'Hard', 'The inverse of sin x is:', 'cos⁻¹x', 'sin⁻¹x', 'tan⁻¹x', 'None', 'sin⁻¹x'),
('JEE Mains', 'Hard', 'If f(x) = x³ - 3x + 1, then f''(x) = ?', '3x² - 3', '3x² + 3', 'x² - 3', '3x³ - 3', '3x² - 3'),
('JEE Mains', 'Hard', 'The power of a lens with focal length 20 cm is:', '+5 D', '-5 D', '+10 D', '-10 D', '+5 D'),
('JEE Mains', 'Hard', 'The total number of valence electrons in CO₂ is:', '12', '16', '20', '24', '16'),
('JEE Mains', 'Hard', 'The total number of 5-digit numbers that can be formed using the digits 1, 2, 3, 4, 5 without repetition is:', '60', '120', '240', '360', '120'),
('JEE Mains', 'Hard', 'The shortest distance between the lines x = 1 + 2t, y = 2 - 3t, z = 3 + 4t and x = 2 + 3s, y = 4 + 5s, z = 6 + 7s is found using:', 'Cross product method', 'Dot product method', 'Projection formula', 'None', 'Cross product method'),
('JEE Mains', 'Hard', 'The general solution of d²y/dx² = 0 is:', 'C₁e^x + C₂e^(-x)', 'C₁x + C₂', 'C₁ cos x + C₂ sin x', 'None', 'C₁x + C₂'),
('JEE Mains', 'Hard', 'The sum of the roots of x³ - 4x² + 3x - 1 = 0 is:', '1', '4', '3', '2', '4'),
('JEE Mains', 'Hard', 'The probability of getting a sum of 7 when rolling two dice is:', '1/6', '1/12', '1/36', '1/3', '1/6');





INSERT INTO ExamPreparation (category, sub_category, question, option_A, option_B, option_C, option_D, correct_answer)
VALUES
('JEE Advanced', 'Easy', 'The SI unit of power is:', 'Joule', 'Watt', 'Newton', 'Pascal', 'Watt'),
('JEE Advanced', 'Easy', 'A car moving with uniform velocity has:', 'Constant acceleration', 'Zero acceleration', 'Increasing velocity', 'None', 'Zero acceleration'),
('JEE Advanced', 'Easy', 'Newton’s first law is also known as the:', 'Law of Momentum', 'Law of Inertia', 'Law of Acceleration', 'Law of Force', 'Law of Inertia'),
('JEE Advanced', 'Easy', 'The force required to stop a moving body is called:', 'Inertia', 'Friction', 'Momentum', 'Impulse', 'Friction'),
('JEE Advanced', 'Easy', 'The value of acceleration due to gravity on Earth is:', '8.9 m/s²', '9.8 m/s²', '10.8 m/s²', '11.8 m/s²', '9.8 m/s²'),
('JEE Advanced', 'Easy', 'The energy of an object due to its motion is:', 'Kinetic Energy', 'Potential Energy', 'Chemical Energy', 'Thermal Energy', 'Kinetic Energy'),
('JEE Advanced', 'Easy', 'A convex lens is also called:', 'Converging lens', 'Diverging lens', 'Flat lens', 'None', 'Converging lens'),
('JEE Advanced', 'Easy', 'A freely falling object has a velocity of:', 'Increasing with time', 'Constant', 'Decreasing', 'Zero', 'Increasing with time'),
('JEE Advanced', 'Easy', 'The unit of resistance is:', 'Volt', 'Ohm', 'Ampere', 'Tesla', 'Ohm'),
('JEE Advanced', 'Easy', 'The atomic number of oxygen is:', '6', '8', '10', '12', '8'),
('JEE Advanced', 'Easy', 'The chemical formula of common salt is:', 'NaOH', 'HCl', 'NaCl', 'KCl', 'NaCl'),
('JEE Advanced', 'Easy', 'The valency of carbon is:', '2', '4', '6', '8', '4'),
('JEE Advanced', 'Easy', 'The most abundant gas in the Earth\'s atmosphere is:', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon', 'Nitrogen'),
('JEE Advanced', 'Easy', 'The chemical name of quicklime is:', 'Ca(OH)₂', 'CaO', 'CaCO₃', 'CaCl₂', 'CaO'),
('JEE Advanced', 'Easy', 'The pH of a neutral solution is:', '7', '5', '10', '1', '7'),
('JEE Advanced', 'Easy', 'The metal that is liquid at room temperature is:', 'Mercury', 'Sodium', 'Aluminum', 'Iron', 'Mercury'),
('JEE Advanced', 'Easy', 'The formula for methane is:', 'CH₄', 'C₂H₆', 'CO₂', 'H₂O', 'CH₄'),
('JEE Advanced', 'Easy', 'The value of sin 30° is:', '1/2', '1', '0', '-1', '1/2'),
('JEE Advanced', 'Easy', 'The area of a circle with radius r is:', '2πr', 'πr²', 'πr³', 'None', 'πr²'),
('JEE Advanced', 'Easy', 'The sum of interior angles of a triangle is:', '90°', '180°', '270°', '360°', '180°'),
('JEE Advanced', 'Easy', 'If x = 2, y = 3, then x² + y² = ?', '13', '12', '10', '15', '13'),
('JEE Advanced', 'Easy', 'The derivative of x² is:', '2x', 'x', '1', 'None', '2x'),
('JEE Advanced', 'Easy', 'The smallest prime number is:', '1', '2', '3', '5', '2'),
('JEE Advanced', 'Easy', 'The value of log 1 is:', '0', '1', '10', 'None', '0'),
('JEE Advanced', 'Easy', 'If a = 3, b = 4, c = 5, then the perimeter of a triangle is:', '12', '10', '9', '15', '12');


INSERT INTO ExamPreparation (category, sub_category, question, option_A, option_B, option_C, option_D, correct_answer) 
VALUES 
('JEE Advanced', 'Medium', 'A ball is thrown upwards with an initial velocity of 20 m/s. The maximum height reached is:', '10 m', '20 m', '40 m', 'None', '20 m'),
('JEE Advanced', 'Medium', 'A solid sphere and a hollow sphere of equal masses are rolled down an incline. Which reaches the bottom first?', 'Solid sphere', 'Hollow sphere', 'Both reach at the same time', 'Depends on material', 'Solid sphere'),
('JEE Advanced', 'Medium', 'The moment of inertia of a solid cylinder about its central axis is:', '1/2 MR²', '2/3 MR²', 'MR²', '3/5 MR²', '1/2 MR²'),
('JEE Advanced', 'Medium', 'A capacitor of 5 μF is connected to a 10 V battery. The charge stored is:', '50 μC', '100 μC', '200 μC', '25 μC', '50 μC'),
('JEE Advanced', 'Medium', 'The efficiency of a Carnot engine working between T₁ = 500 K and T₂ = 300 K is:', '0.3', '0.4', '0.5', '0.6', '0.4'),
('JEE Advanced', 'Medium', 'The equivalent resistance of three 4 Ω resistors connected in parallel is:', '4 Ω', '6 Ω', '4/3 Ω', '3 Ω', '4/3 Ω'),
('JEE Advanced', 'Medium', 'A concave mirror forms a real and same-sized image when the object is placed:', 'At 2F', 'At F', 'At infinity', 'Between F and 2F', 'At 2F'),
('JEE Advanced', 'Medium', 'A wire of resistance R is stretched to double its length. The new resistance is:', '4R', '2R', 'R/2', 'R', '4R'),
('JEE Advanced', 'Medium', 'A transformer is used to:', 'Convert AC to DC', 'Increase power', 'Change voltage levels', 'Increase resistance', 'Change voltage levels'),
('JEE Advanced', 'Medium', 'The hybridization of carbon in CH₄ is:', 'sp', 'sp³', 'sp²', 'None', 'sp³'),
('JEE Advanced', 'Medium', 'The order of acidic strength is:', 'HF > HCl > HBr > HI', 'HI > HBr > HCl > HF', 'HF > HI > HBr > HCl', 'None', 'HI > HBr > HCl > HF'),
('JEE Advanced', 'Medium', 'The IUPAC name of CH₃CH₂OH is:', 'Methanol', 'Ethanol', 'Propanol', 'Butanol', 'Ethanol'),
('JEE Advanced', 'Medium', 'The number of unpaired electrons in Fe²⁺ is:', '4', '3', '2', '5', '4'),
('JEE Advanced', 'Medium', 'The bond angle in H₂O is approximately:', '120°', '104.5°', '180°', '90°', '104.5°'),
('JEE Advanced', 'Medium', 'The molecular shape of NH₃ is:', 'Trigonal planar', 'Trigonal pyramidal', 'Linear', 'Tetrahedral', 'Trigonal pyramidal'),
('JEE Advanced', 'Medium', 'The solubility of a gas in a liquid decreases with:', 'Decreasing temperature', 'Increasing temperature', 'Increasing pressure', 'Adding solute', 'Increasing temperature'),
('JEE Advanced', 'Medium', 'The metal that reacts with water at room temperature is:', 'Sodium', 'Iron', 'Silver', 'Copper', 'Sodium'),
('JEE Advanced', 'Medium', 'The derivative of sin x is:', 'cos x', '-cos x', 'sin x', 'None', 'cos x'),
('JEE Advanced', 'Medium', 'The function f(x) = x³ is:', 'Even', 'Odd', 'Neither', 'Periodic', 'Odd'),
('JEE Advanced', 'Medium', 'The roots of x² - 5x + 6 = 0 are:', '2, 3', '1, 6', '-2, -3', 'None', '2, 3'),
('JEE Advanced', 'Medium', 'The equation of a line passing through (1,2) with slope 3 is:', 'y - 2 = 3(x - 1)', 'y = 3x + 1', 'y = 3x - 2', 'None', 'y - 2 = 3(x - 1)'),
('JEE Advanced', 'Medium', 'The integral of ∫x dx is:', 'x²/2 + C', 'x³/3 + C', 'x + C', 'None', 'x²/2 + C'),
('JEE Advanced', 'Medium', 'The value of lim (x → 0) (sin x)/x is:', '0', '1', 'Infinity', '-1', '1'),
('JEE Advanced', 'Medium', 'If log a = x, then a in terms of x is:', 'e^x', 'ln x', 'a/x', 'None', 'e^x'),
('JEE Advanced', 'Medium', 'The sum of an infinite geometric series with first term a and common ratio r < 1 is:', 'a / (1 - r)', 'a / (1 + r)', 'a(1 - r)', 'None', 'a / (1 - r)');


INSERT INTO ExamPreparation (category, sub_category, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
('JEE Advanced', 'Hard', 'A particle moves in a circular path of radius r with a constant speed v. The magnitude of its acceleration is:', 'v²/r', 'v/r', 'vr', 'v²r', 'v²/r'),
('JEE Advanced', 'Hard', 'A thin uniform rod of mass m and length L rotates about one end with angular velocity ω. The kinetic energy is:', '(1/3) mL²ω²', '(1/2) mL²ω²', '(1/6) mL²ω²', 'mL²ω²', '(1/3) mL²ω²'),
('JEE Advanced', 'Hard', 'A projectile is launched at an angle θ with speed v. The range is given by:', '(v² sin 2θ) / g', '(v² cos 2θ) / g', '(v sin 2θ) / g', 'None', '(v² sin 2θ) / g'),
('JEE Advanced', 'Hard', 'A disc is rolling without slipping with velocity v. The velocity of the contact point with the ground is:', 'Zero', 'v', '2v', 'v/2', 'Zero'),
('JEE Advanced', 'Hard', 'The de Broglie wavelength of an electron moving with velocity v is given by:', 'h/mv', 'h/mv²', 'mv/h', 'h/v', 'h/mv'),
('JEE Advanced', 'Hard', 'A charged particle enters a uniform magnetic field at an angle θ. The path is:', 'Circular', 'Helical', 'Parabolic', 'Straight line', 'Helical'),
('JEE Advanced', 'Hard', 'The intensity of light passing through two crossed polarizers is:', 'I₀ cos²θ', 'I₀ sin²θ', 'I₀', 'I₀/2', 'I₀ cos²θ'),
('JEE Advanced', 'Hard', 'A sphere is floating in water with 75% volume submerged. The density of the sphere is:', '0.75 ρ_water', '1.25 ρ_water', '1.5 ρ_water', '0.5 ρ_water', '0.75 ρ_water'),
('JEE Advanced', 'Hard', 'The heat capacity of a monoatomic ideal gas in an isobaric process is:', '(5/2) R', '(3/2) R', '(7/2) R', '(1/2) R', '(5/2) R'),
('JEE Advanced', 'Hard', 'The rate of a reaction 2A → B is given by Rate = k[A]². The reaction is:', 'Second order', 'First order', 'Zero order', 'None', 'Second order'),
('JEE Advanced', 'Hard', 'The stability order of carbocations is:', 'Tertiary > Secondary > Primary > Methyl', 'Methyl > Primary > Secondary > Tertiary', 'Primary > Secondary > Tertiary > Methyl', 'None', 'Tertiary > Secondary > Primary > Methyl'),
('JEE Advanced', 'Hard', 'The geometry of [Fe(CN)₆]⁴⁻ is:', 'Octahedral', 'Tetrahedral', 'Square planar', 'Trigonal bipyramidal', 'Octahedral'),
('JEE Advanced', 'Hard', 'The major product of 2-bromo-2-methylpropane with alc. KOH is:', '2-methylpropene', '2-butanol', '1-bromobutane', 'None', '2-methylpropene'),
('JEE Advanced', 'Hard', 'The color of CuSO₄·5H₂O is:', 'Blue', 'Green', 'White', 'Red', 'Blue'),
('JEE Advanced', 'Hard', 'The number of possible isomers of C₄H₁₀O is:', '4', '7', '9', '10', '7'),
('JEE Advanced', 'Hard', 'The standard Gibbs free energy change for a spontaneous reaction is:', 'Negative', 'Positive', 'Zero', 'None', 'Negative'),
('JEE Advanced', 'Hard', 'The solubility product expression for Ag₂CrO₄ is:', 'Ksp = [Ag⁺]²[CrO₄²⁻]', 'Ksp = [Ag⁺][CrO₄²⁻]²', 'Ksp = [Ag⁺][CrO₄²⁻]', 'None', 'Ksp = [Ag⁺]²[CrO₄²⁻]'),
('JEE Advanced', 'Hard', 'If f(x) = x³ - 3x² + 4, then f’(x) = 0 at:', 'x = 2', 'x = 1', 'x = -1', 'x = 3', 'x = 2'),
('JEE Advanced', 'Hard', 'The equation of the normal to y = x² at (1,1) is:', 'y - 1 = -2(x - 1)', 'y = 2x + 1', 'y = -2x + 3', 'None', 'y - 1 = -2(x - 1)'),
('JEE Advanced', 'Hard', 'The integral ∫ e^(2x) dx is:', '(1/2) e^(2x) + C', 'e^(2x) + C', '(1/3) e^(2x) + C', 'None', '(1/2) e^(2x) + C'),
('JEE Advanced', 'Hard', 'If z = cosθ + i sinθ, then zⁿ = ?', 'cos(nθ) + i sin(nθ)', 'cos(nθ) - i sin(nθ)', 'cos(nθ)', 'None', 'cos(nθ) + i sin(nθ)'),
('JEE Advanced', 'Hard', 'The value of ∫₀¹ x ln(x) dx is:', '-1/4', '-1/2', '1/4', '1/2', '-1/4'),
('JEE Advanced', 'Hard', 'The radius of curvature at (1,1) for y = x² is:', '(5√5)/4', '5/2', '2√5', 'None', '(5√5)/4'),
('JEE Advanced', 'Hard', 'The number of solutions for sin x = x/2 in [-π, π] is:', '3', '2', '1', '0', '3'),
('JEE Advanced', 'Hard', 'The determinant of a 3×3 orthogonal matrix is:', '±1', '0', '2', 'None', '±1');




INSERT INTO ExamPreparation (category, sub_category, question, option_a, option_b, option_c, option_d, correct_answer) VALUES
('MAH PG CET', 'Easy', 'If APPLE is coded as ELPPA, how is TABLE coded?', 'ELBAT', 'TABEE', 'ABLTE', 'EBLTA', 'ELBAT'),
('MAH PG CET', 'Easy', 'Find the missing number in the series: 2, 6, 12, 20, ?', '30', '28', '32', '34', '30'),
('MAH PG CET', 'Easy', 'If A = 1, B = 2, C = 3, then what is the sum of CAT?', '24', '22', '25', '26', '24'),
('MAH PG CET', 'Easy', 'Which number is missing in 3, 6, 12, 24, ?', '48', '50', '46', '52', '48'),
('MAH PG CET', 'Easy', 'Find the odd one out: Cow, Goat, Sheep, Lizard', 'Lizard', 'Cow', 'Goat', 'Sheep', 'Lizard'),
('MAH PG CET', 'Easy', 'If 1st March is Wednesday, what day will 5th March be?', 'Sunday', 'Monday', 'Tuesday', 'Saturday', 'Sunday'),
('MAH PG CET', 'Easy', 'What is 25% of 200?', '50', '40', '55', '45', '50'),
('MAH PG CET', 'Easy', 'If x + 5 = 10, find x.', '5', '15', '10', '0', '5'),
('MAH PG CET', 'Easy', 'A train travels 60 km in 1 hour. How much will it travel in 3 hours?', '180 km', '120 km', '150 km', '200 km', '180 km'),
('MAH PG CET', 'Easy', 'If the price of 1 apple is ₹10, what is the price of 5 apples?', '₹50', '₹40', '₹60', '₹30', '₹50'),
('MAH PG CET', 'Easy', 'The perimeter of a square with a side length of 4 cm is:', '16 cm', '12 cm', '8 cm', '20 cm', '16 cm'),
('MAH PG CET', 'Easy', 'Find the next number: 5, 10, 15, 20, ?', '25', '30', '35', '40', '25'),
('MAH PG CET', 'Easy', 'Choose the correct synonym of Happy:', 'Joyful', 'Sad', 'Angry', 'Tired', 'Joyful'),
('MAH PG CET', 'Easy', 'Identify the correct spelling:', 'Beautiful', 'Beautifull', 'Beutiful', 'Beautifal', 'Beautiful'),
('MAH PG CET', 'Easy', 'The opposite of Big is:', 'Small', 'Huge', 'Tall', 'Large', 'Small'),
('MAH PG CET', 'Easy', 'He ____ to the market every day.', 'goes', 'go', 'going', 'gone', 'goes'),
('MAH PG CET', 'Easy', 'Identify the correct sentence:', 'She is a good teacher.', 'She are a good teacher.', 'She am a good teacher.', 'She be a good teacher.', 'She is a good teacher.'),
('MAH PG CET', 'Easy', 'Which is a verb?', 'Run', 'Fast', 'Bright', 'Happy', 'Run'),
('MAH PG CET', 'Easy', 'Find the missing figure in the pattern: 🔲 🔳 🔲 🔳 🔲 ?', '🔳', '🔲', '🔴', '⬛', '🔳'),
('MAH PG CET', 'Easy', 'Which shape does not belong?', '🔺', '⚫', '🟢', '🟡', '🔺'),
('MAH PG CET', 'Easy', 'If ⬛ = 1, ⬜ = 2, 🔴 = 3, what is ⬛ + ⬜?', '3', '4', '2', '5', '3'),
('MAH PG CET', 'Easy', 'A cube has how many faces?', '6', '8', '10', '4', '6'),
('MAH PG CET', 'Easy', 'What comes next in the sequence? 🟥 🟦 🟨 🟥 🟦 ?', '🟨', '🟪', '🟩', '⬜', '🟨'),
('MAH PG CET', 'Easy', 'Which figure is symmetrical?', 'Circle', 'Triangle', 'Trapezium', 'Hexagon', 'Circle'),
('MAH PG CET', 'Easy', 'If 🔺 + 🔺 = 🔴, then what is 🔴 - 🔺?', '🔺', '🔴', '🔲', '🟠', '🔺');



INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('MAH PG CET', 'Medium', 'If DOG = 26, CAT = 24, then what is BAT = ?', '23', '22', '21', '25', '23'),
('MAH PG CET', 'Medium', 'Find the missing term: Z, X, V, T, ?', 'R', 'S', 'Q', 'P', 'R'),
('MAH PG CET', 'Medium', 'A is the father of B. C is the mother of A. How is C related to B?', 'Grandmother', 'Aunt', 'Sister', 'Mother', 'Grandmother'),
('MAH PG CET', 'Medium', 'Find the next number in the sequence: 3, 8, 15, 24, ?', '35', '32', '30', '40', '35'),
('MAH PG CET', 'Medium', 'Statements: Some cats are dogs. All dogs are animals. Conclusion: Some cats are animals.', 'True', 'False', 'Can\'t say', 'None of the above', 'True'),
('MAH PG CET', 'Medium', 'If A is 1, B is 2, ..., Z is 26, then what is the sum of PAPER?', '50', '55', '48', '60', '50'),
('MAH PG CET', 'Medium', 'If (x - 2)² = 9, find x.', '5, -1', '4, -2', '6, 0', '3, -3', '5, -1'),
('MAH PG CET', 'Medium', 'A shopkeeper gives 20% discount on an item priced at ₹500. What is the selling price?', '₹400', '₹450', '₹420', '₹460', '₹400'),
('MAH PG CET', 'Medium', 'A sum of money doubles in 4 years at simple interest. What is the annual interest rate?', '25%', '20%', '30%', '40%', '25%'),
('MAH PG CET', 'Medium', 'A car travels at 60 km/h for 2 hours and then at 80 km/h for 3 hours. What is the average speed?', '72 km/h', '70 km/h', '75 km/h', '80 km/h', '72 km/h'),
('MAH PG CET', 'Medium', 'The area of a rectangle is 48 cm². If its length is 8 cm, find its width.', '6 cm', '4 cm', '5 cm', '7 cm', '6 cm'),
('MAH PG CET', 'Medium', 'What is the value of √144 + √81?', '21', '19', '18', '20', '21'),
('MAH PG CET', 'Medium', 'Find the correct synonym of Emphasize:', 'Stress', 'Reduce', 'Ignore', 'Lighten', 'Stress'),
('MAH PG CET', 'Medium', 'Identify the correctly spelled word:', 'Accommodation', 'Acommodation', 'Accomodation', 'Accomadation', 'Accommodation'),
('MAH PG CET', 'Medium', 'Choose the antonym of Expand:', 'Contract', 'Enlarge', 'Grow', 'Inflate', 'Contract'),
('MAH PG CET', 'Medium', 'Fill in the blank: She is interested ____ science.', 'in', 'on', 'with', 'about', 'in'),
('MAH PG CET', 'Medium', 'Choose the correct sentence:', 'They were playing in the garden.', 'They was playing in the garden.', 'They is playing in the garden.', 'They are play in the garden.', 'They were playing in the garden.'),
('MAH PG CET', 'Medium', 'Find the word that is NOT a noun:', 'Quickly', 'Book', 'Table', 'Chair', 'Quickly'),
('MAH PG CET', 'Medium', 'Find the missing figure in the pattern: 🔺 🔺 🔲 🔺 🔺 ?', '🔲', '🔺', '🟦', '⬛', '🔲'),
('MAH PG CET', 'Medium', 'Identify the odd one out:', 'Pentagon', 'Square', 'Rectangle', 'Triangle', 'Pentagon'),
('MAH PG CET', 'Medium', 'If ⬛ = 3, ⬜ = 5, 🔺 = 7, what is ⬛ + 🔺?', '10', '12', '14', '16', '10'),
('MAH PG CET', 'Medium', 'A sphere has how many faces?', '1', '2', '3', '0', '1'),
('MAH PG CET', 'Medium', 'What comes next in the sequence? 🔴 🔵 🔴 🔵 🔴 ?', '🔵', '🔴', '🟢', '⬜', '🔵'),
('MAH PG CET', 'Medium', 'Identify the symmetrical figure:', 'Circle', 'Trapezoid', 'Pentagon', 'Rhombus', 'Circle'),
('MAH PG CET', 'Medium', 'If ⬜ + 🔲 = 🔳, then what is 🔳 - ⬜?', '🔲', '🔳', '🔴', '⬛', '🔲');

INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('MAH PG CET', 'Hard', 'If LOGIC is coded as NQIKG, how is BRAIN coded?', 'DTCMP', 'DSCOQ', 'ETDNR', 'CTBOM', 'DSCOQ'),
('MAH PG CET', 'Hard', 'Find the missing term in the series: 3, 6, 11, 18, 27, ?', '38', '37', '40', '35', '38'),
('MAH PG CET', 'Hard', 'A is the brother of B. C is the father of A. D is the son of C. How is B related to D?', 'Brother or Sister', 'Uncle', 'Cousin', 'Father', 'Brother or Sister'),
('MAH PG CET', 'Hard', 'Statement: Some books are pens. All pens are erasers. Conclusion: Some books are erasers.', 'True', 'False', 'Can\'t say', 'None of the above', 'True'),
('MAH PG CET', 'Hard', 'Identify the next term: M, N, Q, R, U, ?', 'V', 'X', 'Y', 'W', 'V'),
('MAH PG CET', 'Hard', 'In a certain code, 4589 is written as XTBY. What is 6584?', 'YBXT', 'YTXB', 'TXBY', 'XYBT', 'YTXB'),
('MAH PG CET', 'Hard', 'Solve for x: 2x² - 5x - 3 = 0', '3, -0.5', '2, -1', '4, -1', '3, -2', '3, -0.5'),
('MAH PG CET', 'Hard', 'A sum of money at compound interest becomes ₹1600 in 2 years and ₹2560 in 4 years. What is the annual interest rate?', '20%', '25%', '30%', '35%', '20%'),
('MAH PG CET', 'Hard', 'A and B can complete a work in 20 days and 30 days, respectively. If they work together, in how many days will they complete the work?', '12 days', '10 days', '15 days', '8 days', '12 days'),
('MAH PG CET', 'Hard', 'The perimeter of a rectangle is 48 cm. The ratio of length to breadth is 3:1. Find the area.', '108 cm²', '112 cm²', '120 cm²', '96 cm²', '108 cm²'),
('MAH PG CET', 'Hard', 'A train crosses a 250 m platform in 20 seconds and a 150 m bridge in 15 seconds. What is the speed of the train?', '40 m/s', '45 m/s', '50 m/s', '35 m/s', '40 m/s'),
('MAH PG CET', 'Hard', 'Find the next term: 2, 9, 28, 65, ?', '126', '121', '130', '140', '126'),
('MAH PG CET', 'Hard', 'Find the correct synonym of "Obliterate":', 'Destroy', 'Create', 'Build', 'Establish', 'Destroy'),
('MAH PG CET', 'Hard', 'Identify the correct spelling:', 'Exaggerate', 'Exagerate', 'Exagerrate', 'Exaggerrate', 'Exaggerate'),
('MAH PG CET', 'Hard', 'Choose the antonym of "Imminent":', 'Distant', 'Close', 'Immediate', 'Forthcoming', 'Distant'),
('MAH PG CET', 'Hard', 'Fill in the blank: His argument was based ____ logic.', 'on', 'in', 'at', 'with', 'on'),
('MAH PG CET', 'Hard', 'Choose the grammatically correct sentence:', 'He has been working here since 2010.', 'He has been working here for 2010.', 'He has worked here since 2010.', 'He have been working here since 2010.', 'He has been working here since 2010.'),
('MAH PG CET', 'Hard', 'Find the odd one out:', 'Run', 'Swim', 'Walk', 'Happiness', 'Run'),
('MAH PG CET', 'Hard', 'Find the missing figure: 🔵🔴🔵🔴🔵?', '🔴', '🔵', '🟡', '⬜', '🔴'),
('MAH PG CET', 'Hard', 'Identify the odd one out:', 'Hexagon', 'Square', 'Triangle', 'Circle', 'Hexagon'),
('MAH PG CET', 'Hard', 'If ⬛ = 3, ⬜ = 7, 🔺 = 9, then ⬜ + 🔺 = ?', '16', '14', '12', '18', '16'),
('MAH PG CET', 'Hard', 'A solid has 6 faces, 8 vertices, and 12 edges. What is it?', 'Cube', 'Sphere', 'Cylinder', 'Cone', 'Cube'),
('MAH PG CET', 'Hard', 'What comes next in the sequence? 🟥 🟦 🟨 🟥 🟦 ?', '🟨', '🟩', '⬜', '🟠', '🟨'),
('MAH PG CET', 'Hard', 'Which figure is symmetrical?', 'Equilateral Triangle', 'Trapezium', 'Rhombus', 'Pentagon', 'Equilateral Triangle'),
('MAH PG CET', 'Hard', 'If 🔲 + 🔴 = 🔳, then what is 🔳 - 🔴?', '🔲', '🔳', '🔴', '🔺', '🔲');




INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('CTET', 'Easy', 'Which of the following is the national animal of India?', 'Elephant', 'Tiger', 'Lion', 'Leopard', 'Tiger'),
('CTET', 'Easy', 'Which shape has three sides?', 'Triangle', 'Square', 'Rectangle', 'Pentagon', 'Triangle'),
('CTET', 'Easy', 'What is the capital of India?', 'Mumbai', 'New Delhi', 'Kolkata', 'Chennai', 'New Delhi'),
('CTET', 'Easy', 'Which is the largest planet in the Solar System?', 'Earth', 'Venus', 'Jupiter', 'Mars', 'Jupiter'),
('CTET', 'Easy', 'Which organ pumps blood in the human body?', 'Lungs', 'Liver', 'Heart', 'Kidney', 'Heart'),
('CTET', 'Easy', 'Which number comes after 49?', '47', '50', '48', '51', '50'),
('CTET', 'Easy', 'How many vowels are there in the English alphabet?', '4', '10', '5', '6', '5'),
('CTET', 'Easy', 'Which is the smallest continent?', 'Asia', 'Australia', 'Europe', 'Africa', 'Australia'),
('CTET', 'Easy', 'How many months have 31 days?', '7', '6', '5', '8', '7'),
('CTET', 'Easy', 'Which part of the plant makes food?', 'Roots', 'Leaves', 'Stem', 'Flowers', 'Leaves'),
('CTET', 'Easy', 'How many legs does a spider have?', '6', '8', '10', '12', '8'),
('CTET', 'Easy', 'Which of these is a domestic animal?', 'Tiger', 'Cow', 'Lion', 'Elephant', 'Cow'),
('CTET', 'Easy', 'What is 15 + 25?', '30', '35', '40', '45', '40'),
('CTET', 'Easy', 'Which festival is known as the Festival of Lights?', 'Holi', 'Diwali', 'Eid', 'Christmas', 'Diwali'),
('CTET', 'Easy', 'How many hours are there in a day?', '12', '10', '24', '20', '24'),
('CTET', 'Easy', 'What is the color of a ripe banana?', 'Red', 'Green', 'Yellow', 'Blue', 'Yellow'),
('CTET', 'Easy', 'Which gas do humans need to breathe?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen', 'Oxygen'),
('CTET', 'Easy', 'What is the opposite of "Tall"?', 'Short', 'Wide', 'Heavy', 'Thin', 'Short'),
('CTET', 'Easy', 'How many sides does a pentagon have?', '4', '5', '6', '8', '5'),
('CTET', 'Easy', 'Which day comes after Tuesday?', 'Monday', 'Wednesday', 'Thursday', 'Friday', 'Wednesday'),
('CTET', 'Easy', 'Which of these is an odd number?', '16', '20', '13', '18', '13'),
('CTET', 'Easy', 'Which animal gives us wool?', 'Cow', 'Sheep', 'Goat', 'Dog', 'Sheep'),
('CTET', 'Easy', 'What is the currency of India?', 'Dollar', 'Rupee', 'Euro', 'Yen', 'Rupee'),
('CTET', 'Easy', 'What is the primary source of energy for Earth?', 'The Sun', 'The Moon', 'The Stars', 'The Ocean', 'The Sun'),
('CTET', 'Easy', 'How many fingers does a human hand have?', '5', '6', '4', '10', '5');

INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('CTET', 'Hard', 'Which teaching method is best for developing problem-solving skills?', 'Rote memorization', 'Inquiry-based learning', 'Lecture method', 'Dictation', 'Inquiry-based learning'),
('CTET', 'Hard', 'Who proposed the theory of "Zone of Proximal Development (ZPD)"?', 'Jean Piaget', 'B.F. Skinner', 'Lev Vygotsky', 'Erik Erikson', 'Lev Vygotsky'),
('CTET', 'Hard', 'Which part of the brain is responsible for memory and learning?', 'Medulla', 'Hippocampus', 'Cerebellum', 'Hypothalamus', 'Hippocampus'),
('CTET', 'Hard', 'Which of the following is an example of intrinsic motivation?', 'Studying to earn a reward', 'Reading a book out of curiosity', 'Doing homework to avoid punishment', 'Participating in class for extra marks', 'Reading a book out of curiosity'),
('CTET', 'Hard', 'According to Piaget, at which stage does abstract thinking develop?', 'Sensorimotor', 'Preoperational', 'Concrete operational', 'Formal operational', 'Formal operational'),
('CTET', 'Hard', 'Which assessment method best measures a child\'s critical thinking ability?', 'Multiple-choice tests', 'Open-ended questions', 'True/false questions', 'Rote recall tests', 'Open-ended questions'),
('CTET', 'Hard', 'A teacher wants to assess a child\'s reading comprehension. Which method should be used?', 'Dictation', 'Cloze test', 'Spelling test', 'Word-matching', 'Cloze test'),
('CTET', 'Hard', 'Which of the following is an example of scaffolding in education?', 'Assigning more homework', 'Providing hints to help students answer', 'Giving direct answers to students', 'Ignoring struggling students', 'Providing hints to help students answer'),
('CTET', 'Hard', 'In Bloom’s Taxonomy, which level comes after "Understanding"?', 'Remembering', 'Applying', 'Analyzing', 'Evaluating', 'Applying'),
('CTET', 'Hard', 'Which teaching technique is best suited for students with dyslexia?', 'Multisensory approach', 'Reading-only methods', 'Copying from the board', 'Memorization', 'Multisensory approach'),
('CTET', 'Hard', 'What is the full form of ICT in education?', 'Information and Communication Technology', 'Internet and Computer Teaching', 'Interactive Classroom Teaching', 'Integrated Concept Training', 'Information and Communication Technology'),
('CTET', 'Hard', 'Which of these is a characteristic of a constructivist classroom?', 'Teacher-centered learning', 'Active participation by students', 'Passive listening', 'Emphasis on rote learning', 'Active participation by students'),
('CTET', 'Hard', 'What is the main goal of formative assessment?', 'Assigning final grades', 'Providing feedback for improvement', 'Ranking students in class', 'Measuring past knowledge', 'Providing feedback for improvement'),
('CTET', 'Hard', 'What is the best way to teach moral values in the classroom?', 'Giving strict punishments', 'Using real-life examples and discussions', 'Forcing students to follow rules', 'Teaching religious texts', 'Using real-life examples and discussions'),
('CTET', 'Hard', 'Which of these statements is true about metacognition?', 'It is about remembering facts', 'It involves thinking about one\'s own thinking process', 'It focuses only on memorization', 'It does not help students improve learning', 'It involves thinking about one\'s own thinking process'),
('CTET', 'Hard', 'Which of the following is an example of experiential learning?', 'Reading about science experiments', 'Performing a science experiment in a lab', 'Watching a documentary', 'Listening to a lecture', 'Performing a science experiment in a lab'),
('CTET', 'Hard', 'According to Erikson, which stage focuses on identity vs. role confusion?', 'Early childhood', 'Adulthood', 'Adolescence', 'Infancy', 'Adolescence'),
('CTET', 'Hard', 'Which of the following is an example of summative assessment?', 'Classroom discussions', 'Final semester exams', 'Daily quizzes', 'Homework assignments', 'Final semester exams'),
('CTET', 'Hard', 'Which of these is NOT a part of NEP 2020 reforms?', 'Introduction of foundational literacy', 'Abolishing board exams', 'Multidisciplinary education', 'Focus on vocational training', 'Abolishing board exams'),
('CTET', 'Hard', 'Which of the following is an example of differentiated instruction?', 'Providing different types of activities for different learning styles', 'Teaching all students the same way', 'Using only textbook-based instruction', 'Ignoring students with learning difficulties', 'Providing different types of activities for different learning styles'),
('CTET', 'Hard', 'Which instructional strategy is best for developing critical thinking?', 'Project-based learning', 'Rote memorization', 'Copying notes from the board', 'Listening to a lecture', 'Project-based learning'),
('CTET', 'Hard', 'Which factor has the greatest impact on early childhood learning?', 'Watching TV', 'Parental involvement and environment', 'Strict discipline', 'High test scores', 'Parental involvement and environment'),
('CTET', 'Hard', 'Which type of assessment helps identify students with special learning needs?', 'Diagnostic assessment', 'Formative assessment', 'Summative assessment', 'Self-assessment', 'Diagnostic assessment'),
('CTET', 'Hard', 'Which of the following is an example of active learning?', 'Group discussions and peer teaching', 'Silent reading', 'Copying notes', 'Listening to a lecture', 'Group discussions and peer teaching'),
('CTET', 'Hard', 'What is the main focus of inclusive education?', 'Providing equal learning opportunities for all students', 'Teaching only gifted students', 'Separating special needs students', 'Eliminating assessments', 'Providing equal learning opportunities for all students');

INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('CTET', 'Medium', 'Which learning theory emphasizes the role of reinforcement and punishment?', 'Behaviorism', 'Constructivism', 'Humanism', 'Cognitivism', 'Behaviorism'),
('CTET', 'Medium', 'Who introduced the concept of "Multiple Intelligences"?', 'Jean Piaget', 'Howard Gardner', 'Lev Vygotsky', 'Noam Chomsky', 'Howard Gardner'),
('CTET', 'Medium', 'What is the primary focus of formative assessment?', 'Assigning final grades', 'Providing feedback to improve learning', 'Comparing students', 'Measuring intelligence', 'Providing feedback to improve learning'),
('CTET', 'Medium', 'Which of the following is an example of intrinsic motivation?', 'Studying to get a prize', 'Reading a book for personal enjoyment', 'Completing homework to avoid punishment', 'Memorizing notes for an exam', 'Reading a book for personal enjoyment'),
('CTET', 'Medium', 'What is the key feature of child-centered learning?', 'Rote memorization', 'Active participation by students', 'Teacher-focused instruction', 'Passive listening', 'Active participation by students'),
('CTET', 'Medium', 'According to Piaget, at which stage do children develop logical thinking?', 'Preoperational stage', 'Concrete operational stage', 'Formal operational stage', 'Sensorimotor stage', 'Concrete operational stage'),
('CTET', 'Medium', 'Which is an example of scaffolding in education?', 'Providing step-by-step guidance', 'Giving complex problems without help', 'Ignoring struggling students', 'Letting students work alone', 'Providing step-by-step guidance'),
('CTET', 'Medium', 'Which of these is a characteristic of an effective lesson plan?', 'Clearly defined objectives', 'Teaching only one type of learner', 'Focusing only on theory', 'Ignoring student engagement', 'Clearly defined objectives'),
('CTET', 'Medium', 'What is the full form of B.Ed.?', 'Bachelor of English Development', 'Bachelor of Education', 'Basic Education Degree', 'Bachelor of Early Development', 'Bachelor of Education'),
('CTET', 'Medium', 'Which assessment technique is best for evaluating students’ application of knowledge?', 'Project-based learning', 'Rote memorization', 'Copying from a textbook', 'Dictation', 'Project-based learning'),
('CTET', 'Medium', 'What is the best strategy to teach a student with dyslexia?', 'Force them to read aloud', 'Use multisensory teaching methods', 'Ignore spelling mistakes', 'Give only written tests', 'Use multisensory teaching methods'),
('CTET', 'Medium', 'Which educational approach focuses on learning through experience?', 'Experiential learning', 'Lecture method', 'Rote learning', 'Dictation-based learning', 'Experiential learning'),
('CTET', 'Medium', 'What is the primary goal of NEP 2020?', 'Eliminate exams', 'Holistic and multidisciplinary education', 'Focus only on STEM subjects', 'Remove school assessments', 'Holistic and multidisciplinary education'),
('CTET', 'Medium', 'What is the first step in lesson planning?', 'Conducting an exam', 'Setting learning objectives', 'Assigning homework', 'Giving a lecture', 'Setting learning objectives'),
('CTET', 'Medium', 'Which of these is a summative assessment?', 'Group discussion', 'Final term examination', 'Daily classroom activities', 'Peer feedback', 'Final term examination'),
('CTET', 'Medium', 'Which teaching technique is best for students with different learning styles?', 'Differentiated instruction', 'One-size-fits-all teaching', 'Rote memorization', 'Teacher-centered learning', 'Differentiated instruction'),
('CTET', 'Medium', 'Which of the following best describes constructivist learning?', 'Learning through exploration and problem-solving', 'Memorizing facts', 'Passive learning', 'Teacher-controlled learning', 'Learning through exploration and problem-solving'),
('CTET', 'Medium', 'According to Vygotsky, learning is best achieved through:', 'Social interaction and guided learning', 'Individual study', 'Rote learning', 'Independent practice only', 'Social interaction and guided learning'),
('CTET', 'Medium', 'What is the best way to handle a disruptive student in class?', 'Address the issue calmly and privately', 'Punish them in front of classmates', 'Ignore their behavior', 'Remove them from the classroom', 'Address the issue calmly and privately'),
('CTET', 'Medium', 'Which of the following is a feature of inquiry-based learning?', 'Teacher-centered instruction', 'Encouraging students to ask questions and investigate', 'Learning through memorization', 'Passive listening', 'Encouraging students to ask questions and investigate'),
('CTET', 'Medium', 'Which of the following is a sign of a gifted learner?', 'Struggles with all subjects', 'Grasps new concepts quickly', 'Avoids participation in class', 'Relies only on textbooks', 'Grasps new concepts quickly'),
('CTET', 'Medium', 'Which assessment method provides immediate feedback to students?', 'Formative assessment', 'Summative assessment', 'Standardized testing', 'Annual exams', 'Formative assessment'),
('CTET', 'Medium', 'Which strategy helps students develop problem-solving skills?', 'Encouraging them to analyze and think critically', 'Giving direct answers', 'Rote learning', 'Repeating instructions multiple times', 'Encouraging them to analyze and think critically'),
('CTET', 'Medium', 'What is the role of a facilitator in a student-centered classroom?', 'Guiding students to discover knowledge on their own', 'Controlling all learning activities', 'Giving direct answers without explanation', 'Limiting student discussions', 'Guiding students to discover knowledge on their own'),
('CTET', 'Medium', 'Which of the following is an example of cooperative learning?', 'Students working together on a group project', 'Individual learning', 'Teacher-led instruction', 'Silent reading', 'Students working together on a group project');






INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('NEET', 'Easy', 'Which of the following is the powerhouse of the cell?', 'Ribosome', 'Nucleus', 'Mitochondria', 'Golgi apparatus', 'Mitochondria'),
('NEET', 'Easy', 'What is the chemical formula of glucose?', 'C₆H₁₂O₆', 'CH₄', 'CO₂', 'H₂O', 'C₆H₁₂O₆'),
('NEET', 'Easy', 'Which vitamin is produced in the human body when exposed to sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B', 'Vitamin D'),
('NEET', 'Easy', 'What is the functional unit of the kidney?', 'Alveolus', 'Neuron', 'Nephron', 'Glomerulus', 'Nephron'),
('NEET', 'Easy', 'Which blood group is called the universal donor?', 'A+', 'AB+', 'O-', 'B+', 'O-'),
('NEET', 'Easy', 'What is the SI unit of force?', 'Joule', 'Watt', 'Newton', 'Pascal', 'Newton'),
('NEET', 'Easy', 'Which organ is responsible for producing insulin?', 'Liver', 'Pancreas', 'Kidney', 'Lungs', 'Pancreas'),
('NEET', 'Easy', 'Which part of the brain controls balance and coordination?', 'Cerebrum', 'Cerebellum', 'Medulla', 'Hypothalamus', 'Cerebellum'),
('NEET', 'Easy', 'What is the normal pH of human blood?', '6.0', '7.4', '5.5', '8.0', '7.4'),
('NEET', 'Easy', 'Which of the following is a fat-soluble vitamin?', 'Vitamin A', 'Vitamin C', 'Vitamin B12', 'Vitamin B2', 'Vitamin A'),
('NEET', 'Easy', 'What is the main function of hemoglobin?', 'Transport of nutrients', 'Transport of oxygen', 'Production of white blood cells', 'Digestion of proteins', 'Transport of oxygen'),
('NEET', 'Easy', 'Which of the following is an example of a prokaryotic organism?', 'Bacteria', 'Fungi', 'Plants', 'Animals', 'Bacteria'),
('NEET', 'Easy', 'Which process converts glucose into energy in cells?', 'Photosynthesis', 'Respiration', 'Fermentation', 'Transpiration', 'Respiration'),
('NEET', 'Easy', 'Which hormone is called the "fight or flight" hormone?', 'Adrenaline', 'Insulin', 'Thyroxine', 'Estrogen', 'Adrenaline'),
('NEET', 'Easy', 'Which gas is essential for respiration?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen', 'Oxygen'),
('NEET', 'Easy', 'What is the basic structural and functional unit of life?', 'Tissue', 'Cell', 'Organ', 'DNA', 'Cell'),
('NEET', 'Easy', 'Which organ in the human body produces bile?', 'Pancreas', 'Liver', 'Stomach', 'Small intestine', 'Liver'),
('NEET', 'Easy', 'What is the primary function of the large intestine?', 'Digestion of food', 'Absorption of water', 'Secretion of enzymes', 'Protein metabolism', 'Absorption of water'),
('NEET', 'Easy', 'Which component of blood helps in clotting?', 'Red blood cells', 'White blood cells', 'Platelets', 'Plasma', 'Platelets'),
('NEET', 'Easy', 'What is the full form of DNA?', 'Deoxyribonucleic Acid', 'Dextrose Nucleic Acid', 'Dehydrogenated Nucleic Acid', 'Double-stranded Nucleic Acid', 'Deoxyribonucleic Acid'),
('NEET', 'Easy', 'Which part of the human body produces red blood cells?', 'Liver', 'Bone marrow', 'Kidney', 'Spleen', 'Bone marrow'),
('NEET', 'Easy', 'What is the largest organ in the human body?', 'Liver', 'Heart', 'Skin', 'Brain', 'Skin'),
('NEET', 'Easy', 'Which blood vessel carries oxygenated blood from the lungs to the heart?', 'Pulmonary artery', 'Pulmonary vein', 'Aorta', 'Vena cava', 'Pulmonary vein'),
('NEET', 'Easy', 'Which of the following is a non-communicable disease?', 'Tuberculosis', 'Diabetes', 'Malaria', 'Influenza', 'Diabetes'),
('NEET', 'Easy', 'Which enzyme is responsible for breaking down starch into sugar?', 'Pepsin', 'Amylase', 'Trypsin', 'Lipase', 'Amylase');


INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('NEET', 'Medium', 'Which hormone regulates water balance in the body?', 'Insulin', 'Antidiuretic hormone (ADH)', 'Oxytocin', 'Adrenaline', 'Antidiuretic hormone (ADH)'),
('NEET', 'Medium', 'Which organelle is responsible for protein synthesis?', 'Lysosome', 'Ribosome', 'Golgi apparatus', 'Mitochondria', 'Ribosome'),
('NEET', 'Medium', 'What is the primary function of pulmonary veins?', 'Carry oxygenated blood from the heart to the lungs', 'Carry oxygenated blood from the lungs to the heart', 'Carry deoxygenated blood to the lungs', 'Supply oxygen to the heart muscles', 'Carry oxygenated blood from the lungs to the heart'),
('NEET', 'Medium', 'Which part of the nephron is responsible for filtration?', 'Loop of Henle', 'Glomerulus', 'Distal tubule', 'Collecting duct', 'Glomerulus'),
('NEET', 'Medium', 'What is the function of the sinoatrial (SA) node?', 'Pump blood through the heart', 'Act as the natural pacemaker of the heart', 'Filter impurities in the blood', 'Maintain blood pressure', 'Act as the natural pacemaker of the heart'),
('NEET', 'Medium', 'Which enzyme is responsible for breaking down lactose?', 'Maltase', 'Lactase', 'Amylase', 'Pepsin', 'Lactase'),
('NEET', 'Medium', 'What is the main nitrogenous waste in humans?', 'Urea', 'Ammonia', 'Uric acid', 'Creatinine', 'Urea'),
('NEET', 'Medium', 'Which of the following is an example of passive immunity?', 'Vaccination', 'Antibodies passed from mother to child through breast milk', 'Infection recovery', 'Immunization with a weakened pathogen', 'Antibodies passed from mother to child through breast milk'),
('NEET', 'Medium', 'Which structure in plants is responsible for water transport?', 'Phloem', 'Xylem', 'Cambium', 'Parenchyma', 'Xylem'),
('NEET', 'Medium', 'What is the process by which plants lose water in the form of vapor?', 'Respiration', 'Transpiration', 'Photosynthesis', 'Germination', 'Transpiration'),
('NEET', 'Medium', 'What is the full form of ATP?', 'Adenosine Tripeptide', 'Adenosine Triphosphate', 'Adenosine Tetra Phosphorus', 'Acetyl Thiamine Phosphate', 'Adenosine Triphosphate'),
('NEET', 'Medium', 'Which part of the human brain is responsible for memory and learning?', 'Cerebellum', 'Hippocampus', 'Medulla oblongata', 'Hypothalamus', 'Hippocampus'),
('NEET', 'Medium', 'What is the most abundant gas in Earth’s atmosphere?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen', 'Nitrogen'),
('NEET', 'Medium', 'Which of the following is NOT a function of the liver?', 'Detoxification of blood', 'Production of red blood cells', 'Production of bile', 'Storage of glycogen', 'Production of red blood cells'),
('NEET', 'Medium', 'Which of these biomolecules is responsible for carrying genetic information?', 'Proteins', 'DNA', 'Carbohydrates', 'Lipids', 'DNA'),
('NEET', 'Medium', 'Which part of the chloroplast is responsible for light absorption?', 'Stroma', 'Thylakoid membrane', 'Granum', 'Lumen', 'Thylakoid membrane'),
('NEET', 'Medium', 'What type of joint is found between the vertebrae?', 'Hinge joint', 'Cartilaginous joint', 'Ball and socket joint', 'Pivot joint', 'Cartilaginous joint'),
('NEET', 'Medium', 'Which of the following is a greenhouse gas?', 'Methane (CH₄)', 'Oxygen (O₂)', 'Nitrogen (N₂)', 'Helium (He)', 'Methane (CH₄)'),
('NEET', 'Medium', 'What is the primary function of bile in digestion?', 'Digestion of proteins', 'Emulsification of fats', 'Breakdown of carbohydrates', 'Absorption of amino acids', 'Emulsification of fats'),
('NEET', 'Medium', 'Which molecule acts as a biological catalyst?', 'Hormones', 'Enzymes', 'Lipids', 'Carbohydrates', 'Enzymes'),
('NEET', 'Medium', 'Which vitamin helps in blood clotting?', 'Vitamin D', 'Vitamin K', 'Vitamin A', 'Vitamin C', 'Vitamin K'),
('NEET', 'Medium', 'Which of the following is a secondary pollutant?', 'Ozone (O₃)', 'Carbon monoxide (CO)', 'Sulfur dioxide (SO₂)', 'Methane (CH₄)', 'Ozone (O₃)'),
('NEET', 'Medium', 'Which type of muscle is involuntary and striated?', 'Skeletal muscle', 'Cardiac muscle', 'Smooth muscle', 'Voluntary muscle', 'Cardiac muscle'),
('NEET', 'Medium', 'Which organ in the body produces testosterone?', 'Pituitary gland', 'Testes', 'Adrenal gland', 'Thyroid gland', 'Testes'),
('NEET', 'Medium', 'Which bond is present between two amino acids in a protein?', 'Peptide bond', 'Hydrogen bond', 'Ionic bond', 'Covalent bond', 'Peptide bond');


INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('NEET', 'Hard', 'Which of the following is NOT a function of the Golgi apparatus?', 'Protein modification', 'Lysosome formation', 'ATP production', 'Glycoprotein synthesis', 'ATP production'),
('NEET', 'Hard', 'Which of the following is an example of competitive inhibition in enzymes?', 'Non-reversible enzyme inhibition', 'Binding of malonate to succinate dehydrogenase', 'Binding of allosteric regulators', 'Feedback inhibition', 'Binding of malonate to succinate dehydrogenase'),
('NEET', 'Hard', 'Which plant hormone is responsible for phototropism?', 'Cytokinin', 'Auxin', 'Abscisic acid', 'Ethylene', 'Auxin'),
('NEET', 'Hard', 'Which of the following statements is NOT true about plasmids?', 'They are circular DNA molecules', 'They are part of the bacterial chromosome', 'They can replicate independently', 'They can carry antibiotic resistance genes', 'They are part of the bacterial chromosome'),
('NEET', 'Hard', 'Which neurotransmitter is primarily responsible for muscle contraction?', 'Dopamine', 'Acetylcholine', 'Serotonin', 'GABA', 'Acetylcholine'),
('NEET', 'Hard', 'What is the role of topoisomerase in DNA replication?', 'Adds new nucleotides', 'Relieves supercoiling of DNA', 'Seals Okazaki fragments', 'Unwinds DNA strands', 'Relieves supercoiling of DNA'),
('NEET', 'Hard', 'Which of the following is a structural protein?', 'Hemoglobin', 'Collagen', 'Myosin', 'Insulin', 'Collagen'),
('NEET', 'Hard', 'Which law is followed by the Hardy-Weinberg principle?', 'Law of dominance', 'Law of genetic equilibrium', 'Law of independent assortment', 'Law of segregation', 'Law of genetic equilibrium'),
('NEET', 'Hard', 'Which of the following is an example of a C4 plant?', 'Maize', 'Rice', 'Wheat', 'Barley', 'Maize'),
('NEET', 'Hard', 'Which structure in the brain is responsible for regulating body temperature?', 'Cerebrum', 'Hypothalamus', 'Medulla', 'Cerebellum', 'Hypothalamus'),
('NEET', 'Hard', 'What is the genetic disorder caused by a defect in phenylalanine metabolism?', 'Phenylketonuria (PKU)', 'Cystic fibrosis', 'Sickle cell anemia', 'Hemophilia', 'Phenylketonuria (PKU)'),
('NEET', 'Hard', 'Which immunoglobulin is found in breast milk and provides passive immunity to infants?', 'IgM', 'IgG', 'IgA', 'IgE', 'IgA'),
('NEET', 'Hard', 'Which of the following processes is NOT involved in oxidative phosphorylation?', 'Electron transport chain', 'Substrate-level phosphorylation', 'ATP synthesis', 'Proton gradient formation', 'Substrate-level phosphorylation'),
('NEET', 'Hard', 'Which hormone is responsible for uterine contractions during childbirth?', 'Prolactin', 'Oxytocin', 'Estrogen', 'Progesterone', 'Oxytocin'),
('NEET', 'Hard', 'What is the correct sequence of events in muscle contraction?', 'Myosin binding → Calcium release → Actin exposure', 'Calcium release → Troponin activation → Myosin binding → Contraction', 'Troponin activation → ATP hydrolysis → Calcium release', 'ATP hydrolysis → Myosin binding → Actin exposure', 'Calcium release → Troponin activation → Myosin binding → Contraction'),
('NEET', 'Hard', 'Which process increases genetic variability during meiosis?', 'DNA replication', 'Crossing over', 'Cytokinesis', 'RNA transcription', 'Crossing over'),
('NEET', 'Hard', 'Which organelle is involved in apoptosis (programmed cell death)?', 'Mitochondria', 'Ribosomes', 'Lysosomes', 'Golgi apparatus', 'Mitochondria'),
('NEET', 'Hard', 'Which of the following is NOT a function of the liver?', 'Production of digestive enzymes', 'Detoxification of blood', 'Storage of glycogen', 'Bile secretion', 'Production of digestive enzymes'),
('NEET', 'Hard', 'Which of the following is an example of incomplete dominance?', 'Pink flowers in snapdragons (cross of red and white flowers)', 'Blood group inheritance', 'Eye color in humans', 'Sickle cell trait', 'Pink flowers in snapdragons (cross of red and white flowers)'),
('NEET', 'Hard', 'Which phase of the cardiac cycle is responsible for ventricular contraction?', 'Diastole', 'Systole', 'Relaxation', 'Atrial filling', 'Systole'),
('NEET', 'Hard', 'Which of the following diseases is caused by a protozoan?', 'Tuberculosis', 'Malaria', 'Typhoid', 'Cholera', 'Malaria'),
('NEET', 'Hard', 'Which is the most common type of RNA found in cells?', 'mRNA', 'rRNA', 'tRNA', 'hnRNA', 'rRNA'),
('NEET', 'Hard', 'Which part of the human nephron is impermeable to water?', 'Proximal convoluted tubule', 'Descending loop of Henle', 'Ascending loop of Henle', 'Collecting duct', 'Ascending loop of Henle'),
('NEET', 'Hard', 'Which vitamin is necessary for calcium absorption in the intestine?', 'Vitamin D', 'Vitamin A', 'Vitamin K', 'Vitamin B12', 'Vitamin D'),
('NEET', 'Hard', 'Which enzyme is responsible for DNA replication in prokaryotes?', 'DNA polymerase I', 'DNA polymerase III', 'RNA polymerase', 'Helicase', 'DNA polymerase III');







INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('MAH-CET-UG', 'Hard', 'What is the value of log₂ 32?', '5', '4', '6', '10', '5'),
('MAH-CET-UG', 'Hard', 'Which of the following compounds has the highest boiling point?', 'CH₄', 'H₂O', 'NH₃', 'CO₂', 'H₂O'),
('MAH-CET-UG', 'Hard', 'Which one of the following is NOT an inert gas?', 'Neon', 'Argon', 'Krypton', 'Oxygen', 'Oxygen'),
('MAH-CET-UG', 'Hard', 'What is the solution of x in the equation: 3x + 5 = 14?', '5', '2', '3', '4', '3'),
('MAH-CET-UG', 'Hard', 'Which of the following is a characteristic of a perfectly competitive market?', 'Single seller', 'Price discrimination', 'Free entry and exit of firms', 'Product differentiation', 'Free entry and exit of firms'),
('MAH-CET-UG', 'Hard', 'What is the smallest unit of genetic material?', 'Gene', 'Chromosome', 'DNA', 'Nucleus', 'Gene'),
('MAH-CET-UG', 'Hard', 'If a car travels at 60 km/hr for 3 hours, how far does it travel?', '120 km', '150 km', '180 km', '210 km', '180 km'),
('MAH-CET-UG', 'Hard', 'Which of the following is the best conductor of electricity?', 'Silver', 'Copper', 'Iron', 'Aluminum', 'Silver'),
('MAH-CET-UG', 'Hard', 'Which part of the brain controls balance and coordination?', 'Cerebrum', 'Cerebellum', 'Medulla', 'Hypothalamus', 'Cerebellum'),
('MAH-CET-UG', 'Hard', 'Which among the following is NOT a fundamental right in India?', 'Right to Equality', 'Right to Freedom', 'Right to Property', 'Right against Exploitation', 'Right to Property'),
('MAH-CET-UG', 'Hard', 'What is the unit of electric resistance?', 'Watt', 'Coulomb', 'Ohm', 'Ampere', 'Ohm'),
('MAH-CET-UG', 'Hard', 'What is the acceleration due to gravity on Earth?', '9.8 m/s²', '8.9 m/s²', '10.2 m/s²', '9.2 m/s²', '9.8 m/s²'),
('MAH-CET-UG', 'Hard', 'Which of the following is a greenhouse gas?', 'Oxygen', 'Methane', 'Nitrogen', 'Hydrogen', 'Methane'),
('MAH-CET-UG', 'Hard', 'Which of the following is NOT a prime number?', '17', '23', '21', '29', '21'),
('MAH-CET-UG', 'Hard', 'Who is known as the "Father of Indian Constitution"?', 'Mahatma Gandhi', 'Dr. B.R. Ambedkar', 'Jawaharlal Nehru', 'Sardar Patel', 'Dr. B.R. Ambedkar'),
('MAH-CET-UG', 'Hard', 'Which of the following waves has the highest energy?', 'Radio waves', 'Gamma rays', 'Infrared', 'Microwaves', 'Gamma rays'),
('MAH-CET-UG', 'Hard', 'What is the chemical formula of sulfuric acid?', 'HCl', 'HNO₃', 'H₂SO₄', 'H₂CO₃', 'H₂SO₄'),
('MAH-CET-UG', 'Hard', 'Which of the following is the correct SI unit of power?', 'Newton', 'Watt', 'Pascal', 'Joule', 'Watt'),
('MAH-CET-UG', 'Hard', 'What is the mode of reproduction in Amoeba?', 'Sexual', 'Binary fission', 'Budding', 'Spore formation', 'Binary fission'),
('MAH-CET-UG', 'Hard', 'Which Indian state has the highest literacy rate?', 'Maharashtra', 'Kerala', 'Tamil Nadu', 'Karnataka', 'Kerala'),
('MAH-CET-UG', 'Hard', 'What is the pH of a neutral solution?', '5', '7', '9', '12', '7'),
('MAH-CET-UG', 'Hard', 'Which metal is used in making filaments of an electric bulb?', 'Copper', 'Tungsten', 'Iron', 'Silver', 'Tungsten'),
('MAH-CET-UG', 'Hard', 'What is the sum of the angles in a triangle?', '90°', '270°', '180°', '360°', '180°'),
('MAH-CET-UG', 'Hard', 'Who is the first Indian woman to go to space?', 'Kalpana Chawla', 'Rani Laxmibai', 'Indira Gandhi', 'Kiran Bedi', 'Kalpana Chawla'),
('MAH-CET-UG', 'Hard', 'Which of the following is NOT a vector quantity?', 'Mass', 'Velocity', 'Acceleration', 'Force', 'Mass');



INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('MAH-CET-UG', 'Easy', 'What is the value of (25)^(1/2)?', '10', '5', '15', '20', '5'),
('MAH-CET-UG', 'Easy', 'Which of the following is a primary color?', 'Green', 'Orange', 'Red', 'Pink', 'Red'),
('MAH-CET-UG', 'Easy', 'What is the capital of Maharashtra?', 'Nashik', 'Pune', 'Mumbai', 'Nagpur', 'Mumbai'),
('MAH-CET-UG', 'Easy', 'Which planet is known as the "Red Planet"?', 'Mars', 'Venus', 'Jupiter', 'Saturn', 'Mars'),
('MAH-CET-UG', 'Easy', 'Who wrote the national anthem of India?', 'Rabindranath Tagore', 'Mahatma Gandhi', 'Subhash Chandra Bose', 'Jawaharlal Nehru', 'Rabindranath Tagore'),
('MAH-CET-UG', 'Easy', 'What is the chemical symbol of water?', 'H2', 'CO2', 'H2O', 'O2', 'H2O'),
('MAH-CET-UG', 'Easy', 'Which of the following is a type of energy?', 'Kilogram', 'Kinetic', 'Meter', 'Centimeter', 'Kinetic'),
('MAH-CET-UG', 'Easy', 'Which is the smallest unit of matter?', 'Atom', 'Molecule', 'Cell', 'Electron', 'Atom'),
('MAH-CET-UG', 'Easy', 'Which gas is essential for human respiration?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'Oxygen'),
('MAH-CET-UG', 'Easy', 'Who is known as the "Missile Man of India"?', 'Vikram Sarabhai', 'Dr. A.P.J. Abdul Kalam', 'Homi Bhabha', 'C.V. Raman', 'Dr. A.P.J. Abdul Kalam'),
('MAH-CET-UG', 'Easy', 'What is 15 + 20?', '30', '35', '40', '50', '35'),
('MAH-CET-UG', 'Easy', 'Which is the longest river in India?', 'Yamuna', 'Ganga', 'Brahmaputra', 'Krishna', 'Ganga'),
('MAH-CET-UG', 'Easy', 'Which one is a domestic animal?', 'Cow', 'Tiger', 'Lion', 'Elephant', 'Cow'),
('MAH-CET-UG', 'Easy', 'Which festival is known as the festival of lights?', 'Holi', 'Diwali', 'Navratri', 'Eid', 'Diwali'),
('MAH-CET-UG', 'Easy', 'What is the square of 8?', '64', '16', '32', '128', '64'),
('MAH-CET-UG', 'Easy', 'Which of these is a renewable energy source?', 'Coal', 'Petrol', 'Solar energy', 'Diesel', 'Solar energy'),
('MAH-CET-UG', 'Easy', 'What is the capital of India?', 'Mumbai', 'Chennai', 'Kolkata', 'New Delhi', 'New Delhi'),
('MAH-CET-UG', 'Easy', 'Which is the national bird of India?', 'Eagle', 'Crow', 'Peacock', 'Sparrow', 'Peacock'),
('MAH-CET-UG', 'Easy', 'Who discovered gravity?', 'Isaac Newton', 'Albert Einstein', 'Thomas Edison', 'Charles Darwin', 'Isaac Newton'),
('MAH-CET-UG', 'Easy', 'Which of these is a computer part?', 'Monitor', 'Eraser', 'Pencil', 'Notebook', 'Monitor'),
('MAH-CET-UG', 'Easy', 'Which is the largest continent?', 'Europe', 'Asia', 'Africa', 'Australia', 'Asia'),
('MAH-CET-UG', 'Easy', 'What is the freezing point of water in Celsius?', '0°C', '100°C', '-10°C', '10°C', '0°C'),
('MAH-CET-UG', 'Easy', 'Which number is an even number?', '25', '31', '18', '27', '18'),
('MAH-CET-UG', 'Easy', 'Which is the national flower of India?', 'Rose', 'Lotus', 'Sunflower', 'Lily', 'Lotus'),
('MAH-CET-UG', 'Easy', 'Which sport is associated with Wimbledon?', 'Cricket', 'Football', 'Tennis', 'Basketball', 'Tennis');


INSERT INTO ExamPreparation (category, sub_category, question, option_a,  option_b, option_c, option_d, correct_answer) VALUES
('MAH-CET-UG', 'Medium', 'What is the value of (25)^(1/2)?', '10', '5', '15', '20', '5'),
('MAH-CET-UG', 'Medium', 'Which of the following is a primary color?', 'Green', 'Orange', 'Red', 'Pink', 'Red'),
('MAH-CET-UG', 'Medium', 'What is the capital of Maharashtra?', 'Nashik', 'Pune', 'Mumbai', 'Nagpur', 'Mumbai'),
('MAH-CET-UG', 'Medium', 'Which planet is known as the "Red Planet"?', 'Mars', 'Venus', 'Jupiter', 'Saturn', 'Mars'),
('MAH-CET-UG', 'Medium', 'Who wrote the national anthem of India?', 'Rabindranath Tagore', 'Mahatma Gandhi', 'Subhash Chandra Bose', 'Jawaharlal Nehru', 'Rabindranath Tagore'),
('MAH-CET-UG', 'Medium', 'What is the chemical symbol of water?', 'H2', 'CO2', 'H2O', 'O2', 'H2O'),
('MAH-CET-UG', 'Medium', 'Which of the following is a type of energy?', 'Kilogram', 'Kinetic', 'Meter', 'Centimeter', 'Kinetic'),
('MAH-CET-UG', 'Medium', 'Which is the smallest unit of matter?', 'Atom', 'Molecule', 'Cell', 'Electron', 'Atom'),
('MAH-CET-UG', 'Medium', 'Which gas is essential for human respiration?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'Oxygen'),
('MAH-CET-UG', 'Medium', 'Who is known as the "Missile Man of India"?', 'Vikram Sarabhai', 'Dr. A.P.J. Abdul Kalam', 'Homi Bhabha', 'C.V. Raman', 'Dr. A.P.J. Abdul Kalam'),
('MAH-CET-UG', 'Medium', 'What is 15 + 20?', '30', '35', '40', '50', '35'),
('MAH-CET-UG', 'Medium', 'Which is the longest river in India?', 'Yamuna', 'Ganga', 'Brahmaputra', 'Krishna', 'Ganga'),
('MAH-CET-UG', 'Medium', 'Which one is a domestic animal?', 'Cow', 'Tiger', 'Lion', 'Elephant', 'Cow'),
('MAH-CET-UG', 'Medium', 'Which festival is known as the festival of lights?', 'Holi', 'Diwali', 'Navratri', 'Eid', 'Diwali'),
('MAH-CET-UG', 'Medium', 'What is the square of 8?', '64', '16', '32', '128', '64'),
('MAH-CET-UG', 'Medium', 'Which of these is a renewable energy source?', 'Coal', 'Petrol', 'Solar energy', 'Diesel', 'Solar energy'),
('MAH-CET-UG', 'Medium', 'What is the capital of India?', 'Mumbai', 'Chennai', 'Kolkata', 'New Delhi', 'New Delhi'),
('MAH-CET-UG', 'Medium', 'Which is the national bird of India?', 'Eagle', 'Crow', 'Peacock', 'Sparrow', 'Peacock'),
('MAH-CET-UG', 'Medium', 'Who discovered gravity?', 'Isaac Newton', 'Albert Einstein', 'Thomas Edison', 'Charles Darwin', 'Isaac Newton'),
('MAH-CET-UG', 'Medium', 'Which of these is a computer part?', 'Monitor', 'Eraser', 'Pencil', 'Notebook', 'Monitor'),
('MAH-CET-UG', 'Medium', 'Which is the largest continent?', 'Europe', 'Asia', 'Africa', 'Australia', 'Asia'),
('MAH-CET-UG', 'Medium', 'What is the freezing point of water in Celsius?', '0°C', '100°C', '-10°C', '10°C', '0°C'),
('MAH-CET-UG', 'Medium', 'Which number is an even number?', '25', '31', '18', '27', '18'),
('MAH-CET-UG', 'Medium', 'Which is the national flower of India?', 'Rose', 'Lotus', 'Sunflower', 'Lily', 'Lotus'),
('MAH-CET-UG', 'Medium', 'Which sport is associated with Wimbledon?', 'Cricket', 'Football', 'Tennis', 'Basketball', 'Tennis');
