CREATE TABLE RetroArcadeGames (
    question_id INT AUTO_INCREMENT PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);
INSERT INTO RetroArcadeGames (question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('Which classic arcade game featured a yellow circle eating pellets while avoiding ghosts?', 'Space Invaders', 'Pac-Man', 'Donkey Kong', 'Galaga', 'B'),
('What year was the game Space Invaders released?', '1972', '1977', '1980', '1985', 'B'),
('In Donkey Kong, who is the main character trying to rescue?', 'Pauline', 'Daisy', 'Zelda', 'Princess Peach', 'A'),
('Which retro arcade game featured a paddle and a ball, with the goal to break bricks?', 'Asteroids', 'Pong', 'Breakout', 'Frogger', 'C'),
('What classic arcade game involved jumping over logs and avoiding traffic?', 'Pac-Man', 'Frogger', 'Galaga', 'Missile Command', 'B'),
('Which arcade game featured a spaceship shooting aliens, often referred to as a precursor to Space Invaders?', 'Asteroids', 'Galaga', 'Missile Command', 'Defender', 'A'),
('Which of the following was the first game to feature Mario as a playable character?', 'Super Mario Bros.', 'Donkey Kong', 'Mario Kart', 'Mario Party', 'B'),
('Which arcade game had players control a ship to avoid and destroy asteroids in outer space?', 'Missile Command', 'Centipede', 'Asteroids', 'Galaga', 'C'),
('In Ms. Pac-Man, which of the following changes was made from the original Pac-Man?', 'The maze design changed', 'The ghost behavior was altered', 'The color scheme was brighter', 'The player could jump', 'A'),
('Which arcade game featured a giant ape that threw barrels to stop a man from rescuing a woman?', 'Donkey Kong', 'King Kong', 'Mario Bros.', 'Galaga', 'A'),
('In the game Tempest, what was the shape of the playing field?', 'Circular', 'Square', 'Triangular', 'Hexagonal', 'A'),
('Which arcade game was known for its unique trackball controller, often used in a game involving a spider and insects?', 'Centipede', 'Frogger', 'Missile Command', 'Pac-Man', 'A'),
('In which arcade game did players control a ship that rotated to shoot enemies while avoiding flying saucers and asteroids?', 'Missile Command', 'Space Invaders', 'Asteroids', 'Galaga', 'C'),
('In the arcade game Missile Command, what was the primary objective?', 'To launch missiles at aliens', 'To protect cities from incoming missiles', 'To rescue hostages', 'To collect coins', 'B'),
('Which game introduced the famous character "Q*bert"?', 'Qbert', 'Space Invaders', 'Donkey Kong', 'Galaga', 'A'),
('Which retro arcade game had players attempt to eat all the dots while avoiding ghosts?', 'Pac-Man', 'Frogger', 'Space Invaders', 'Centipede', 'A'),
('Which 1980 arcade game features a space ship fighting off waves of alien attackers and had a precursor to the "power-up" concept?', 'Galaga', 'Space Invaders', 'Missile Command', 'Asteroids', 'A'),
('In Berserk (1980), what was the primary goal of the player?', 'To collect treasure', 'To avoid robots', 'To fight enemy soldiers', 'To escape mazes', 'B'),
('Which classic arcade game introduced the concept of shooting from a fixed position to clear waves of enemies?', 'Space Invaders', 'Asteroids', 'Centipede', 'Galaga', 'A'),
('Which classic arcade game features a jumping hero that avoids obstacles like barrels and jumping over gaps to save his girlfriend?', 'Donkey Kong', 'Mario Bros.', 'Pac-Man', 'Galaga', 'A'),
('What color was the first version of the Pac-Man maze?', 'Blue', 'Yellow', 'Red', 'Green', 'A'),
('What was the name of the arcade game that involved a hero using a whip to rescue damsels in distress while avoiding enemies?', 'Dig Dug', 'Pitfall!', 'Frogger', 'Q*bert', 'B'),
('Which retro game features a vertical shooter where the player moves a ship and shoots at advancing enemies?', 'Galaga', 'Space Invaders', 'Missile Command', 'Asteroids', 'A'),
('In which arcade game did a player control a group of frogs trying to cross roads and rivers?', 'Space Invaders', 'Pac-Man', 'Frogger', 'Q*bert', 'C'),
('Which arcade game used a joystick and button to shoot aliens that invade Earth?', 'Missile Command', 'Space Invaders', 'Asteroids', 'Donkey Kong', 'B');


CREATE TABLE BoardPuzzles (
    question_id INT AUTO_INCREMENT PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);
INSERT INTO BoardPuzzles (question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('Which of the following board games is played with 64 squares on a grid and involves strategic movement of pieces like pawns, knights, and queens?', 'Chess', 'Checkers', 'Backgammon', 'Go', 'A'),
('Which puzzle involves fitting various-shaped pieces together to form a complete image?', 'Crossword', 'Sudoku', 'Jigsaw Puzzle', 'Tangram', 'C'),
('Which board game is known for its theme of buying, trading, and developing properties?', 'Risk', 'Monopoly', 'Clue', 'Scrabble', 'B'),
('What is the main objective in the game of Clue (or Cluedo)?', 'To find a hidden treasure', 'To solve a murder mystery', 'To build a house', 'To complete a crossword puzzle', 'B'),
('Which puzzle requires players to fill a 9x9 grid with numbers from 1 to 9, ensuring each row, column, and region contains no repeating numbers?', 'Crossword', 'Sudoku', 'Kakuro', 'Boggle', 'B'),
('Which board game is played on a 15x15 grid using letter tiles to form words?', 'Scrabble', 'Boggle', 'Word Search', 'Hangman', 'A'),
('In which game do players use dice to move pieces along a track and aim to reach the finish line first?', 'Risk', 'Snakes and Ladders', 'Sorry!', 'Chess', 'B'),
('Which board game features a world map and is played by controlling armies and attempting to conquer territories?', 'Settlers of Catan', 'Risk', 'Ticket to Ride', 'Monopoly', 'B'),
('Which puzzle involves a square divided into seven pieces that can be rearranged to form different shapes?', 'Jigsaw Puzzle', 'Tangram', 'Crossword', 'Rubik’s Cube', 'B'),
('Which classic board game involves moving pieces on a board, collecting resources, and building settlements?', 'Chess', 'Settlers of Catan', 'Risk', 'Monopoly', 'B'),
('In which puzzle game do players rotate and drop different-shaped blocks to create complete lines?', 'Jenga', 'Tetris', 'Pictionary', 'Scrabble', 'B'),
('In which classic board game do players attempt to solve a murder mystery by guessing the murderer, the weapon, and the location?', 'Battleship', 'Clue', 'Risk', 'Monopoly', 'B'),
('Which board game involves guessing a word or phrase based on drawing clues?', 'Scrabble', 'Pictionary', 'Charades', 'Scattergories', 'B'),
('Which board game is played by moving pegs around a board with the goal of being the first to get all your pieces around the board?', 'Sorry!', 'Monopoly', 'Risk', 'Clue', 'A'),
('In which game do players take turns adding pieces to a grid, trying to connect four of their pieces in a row?', 'Connect Four', 'Tic-Tac-Toe', 'Checkers', 'Chess', 'A'),
('Which classic puzzle features a 3x3x3 cube with each side displaying a different solid color?', 'Jenga', 'Rubik’s Cube', 'Sudoku', 'Tangram', 'B'),
('Which game involves players placing X''s and O''s in a 3x3 grid to form a straight line?', 'Connect Four', 'Chess', 'Tic-Tac-Toe', 'Scrabble', 'C'),
('In Battleship, what is the primary objective of the game?', 'To conquer territories', 'To sink the opponent''s ships', 'To complete a crossword', 'To form words with letter tiles', 'B'),
('Which board game is known for its property trading mechanics and the goal of bankrupting opponents?', 'Clue', 'Monopoly', 'Risk', 'Catan', 'B'),
('Which popular puzzle consists of a large square grid where some cells are pre-filled with numbers, and others need to be filled based on specific rules?', 'Sudoku', 'Jigsaw Puzzle', 'Crossword Puzzle', 'Kakuro', 'A'),
('Which of the following board games has its origins in ancient India and involves moving pieces based on dice rolls to reach a goal?', 'Chess', 'Snakes and Ladders', 'Backgammon', 'Go', 'B'),
('In which puzzle game do players need to arrange tiles on a board to form words from a given set of letters?', 'Scrabble', 'Word Search', 'Boggle', 'Hangman', 'A'),
('What is the primary objective in the game Go?', 'To solve a puzzle', 'To capture the opponent’s pieces', 'To reach the center of the board', 'To create shapes with tiles', 'B'),
('Which puzzle game involves filling in a grid with numbers from 1 to 9, ensuring no number repeats in any row, column, or block?', 'Sudoku', 'Kakuro', 'Kakuro', 'Rubik''s Cube', 'A'),
('Which board game involves players solving clues about a murder and trying to deduce the murderer, the weapon, and the location?', 'Risk', 'Clue', 'Scrabble', 'Battleship', 'B');


CREATE TABLE FunFacts (
    question_id INT AUTO_INCREMENT PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);
INSERT INTO FunFacts (question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('What do you call fake spaghetti?', 'Impasta', 'Noodle-not', 'Pasta-lie', 'Faux-pasta', 'A'),
('Why don’t skeletons fight each other?', 'They are too scared', 'They don’t have the guts', 'They can’t find their weapons', 'They’re always too busy', 'B'),
('What did one ocean say to the other ocean?', '“Let’s make waves!”', '“Nothing, it just waved.”', '“I’m feeling salty!”', '“You shore are fun!”', 'B'),
('Why don’t oysters donate to charity?', 'They are too shellfish', 'They are afraid of giving too much', 'They don’t know how to write checks', 'They always clam up', 'A'),
('What do you call cheese that isn’t yours?', 'Nacho cheese', 'Stolen cheese', 'Borrowed cheese', 'Cheddar not yours', 'A'),
('What did the grape say when it got stepped on?', '“Ouch, that’s a crush!”', '“I’m feeling wine!”', '“I’m squashed!”', '“You’re grape!”', 'A'),
('Why did the scarecrow win an award?', 'He was outstanding in his field', 'He was truly terrifying', 'He had a great sense of humor', 'He had a strong work ethic', 'A'),
('What does a cloud wear under his raincoat?', 'Thunderpants', 'Lightning shorts', 'Sky-high socks', 'Waterboots', 'A'),
('Why don’t eggs tell each other secrets?', 'They might crack up', 'They could scramble', 'They’re too hard to crack', 'They just don’t have the shell to do it', 'B'),
('What’s orange and sounds like a parrot?', 'A carrot', 'A pumpkin', 'A tangerine', 'A mango', 'A'),
('What do you call an alligator in a vest?', 'An investigator', 'A gator with style', 'A fashion gator', 'A sharp-dressed reptile', 'A'),
('Why did the math book look sad?', 'It had too many problems', 'It didn’t have any solutions', 'It lost its function', 'It couldn’t find its angle', 'A'),
('Why did the bicycle fall over?', 'It was tired', 'It had a flat', 'It was unbalanced', 'It was too wheelie', 'A'),
('What did the banana say to the dog?', '“Banana split!”', '“You’re so apeeling!”', '“I’m going bananas!”', '“Let’s split!”', 'B'),
('Why did the tomato turn red?', 'It saw the salad dressing', 'It was embarrassed', 'It was ripe', 'It was caught in a ketchup factory', 'A'),
('What did one wall say to the other wall?', '“I’ll meet you at the corner.”', '“Stop leaning on me!”', '“We need to stick together.”', '“You’re so transparent.”', 'A'),
('What did the zero say to the eight?', '“Nice belt!”', '“You’re looking number one!”', '“You’re so full of yourself!”', '“I’m trying to catch up!”', 'A'),
('What do you call a pile of cats?', 'A cat-tastrophe', 'A meow-splosion', 'A cat-astrophe', 'A clowder', 'D'),
('Why can’t your nose be 12 inches long?', 'Because then it would be a foot', 'It would get in the way', 'It would be too big for your face', 'You’d need a bigger hat', 'A'),
('Why don’t skeletons ever use cell phones?', 'They don’t have fingers', 'They can’t find the right number', 'They hate conversations', 'They have no body to call', 'D'),
('What do you call a dinosaur with an extensive vocabulary?', 'A thesaurus', 'A paleontologist', 'A word-saurus', 'A grammar rex', 'A'),
('Why did the computer go to the doctor?', 'It had a virus', 'It was feeling buggy', 'It was malfunctioning', 'It had a hard drive', 'A'),
('What’s brown and sticky?', 'A stick', 'Chocolate syrup', 'Peanut butter', 'A muddy shoe', 'A'),
('What do you call a dog magician?', 'A labracadabrador', 'A poodle trickster', 'A woof wizard', 'A barko', 'A'),
('Why don’t skeletons ever fight?', 'They don’t have the strength', 'They’re afraid of breaking a bone', 'They don’t have enough backbone', 'They’re too soft', 'C');


CREATE TABLE FoodDrink (
    question_id INT AUTO_INCREMENT PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);
INSERT INTO FoodDrink (question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('Which fruit is known as the "king of fruits" and has a strong, distinctive odor?', 'Durian', 'Mango', 'Banana', 'Pineapple', 'A'),
('Which type of pasta is shaped like small rice grains and often used in soups?', 'Penne', 'Fusilli', 'Orzo', 'Farfalle', 'C'),
('What is the primary ingredient in traditional Japanese miso soup?', 'Soybean paste', 'Fish stock', 'Tofu', 'Seaweed', 'A'),
('What is the name of the Italian dish consisting of a thin, round base of dough topped with tomato sauce, cheese, and various other ingredients?', 'Focaccia', 'Risotto', 'Pizza', 'Calzone', 'C'),
('Which vegetable is known as "courgette" in British English?', 'Carrot', 'Cucumber', 'Zucchini', 'Eggplant', 'C'),
('Which country is credited with the invention of the croissant?', 'France', 'Italy', 'Austria', 'Germany', 'C'),
('What is the main ingredient in the Mexican dish guacamole?', 'Tomatoes', 'Avocado', 'Cucumber', 'Corn', 'B'),
('Which of these alcoholic drinks is made primarily from fermented grapes?', 'Whiskey', 'Vodka', 'Beer', 'Wine', 'D'),
('What type of meat is traditionally used in a shepherd''s pie?', 'Pork', 'Chicken', 'Beef', 'Lamb', 'D'),
('What is the name of the Italian rice dish cooked in broth and stirred constantly to achieve a creamy consistency?', 'Polenta', 'Risotto', 'Frittata', 'Gnocchi', 'B'),
('Which fruit is used to make guacamole?', 'Papaya', 'Mango', 'Avocado', 'Kiwi', 'C'),
('Which of the following is the primary ingredient in the French dish "ratatouille"?', 'Potatoes', 'Tomatoes', 'Eggplant', 'Mushrooms', 'B'),
('Which type of bean is the main ingredient in a traditional Mexican refried beans recipe?', 'Pinto beans', 'Kidney beans', 'Black beans', 'Garbanzo beans', 'A'),
('Which of the following is a type of fermented milk drink originating from Russia and Eastern Europe?', 'Kefir', 'Buttermilk', 'Lassi', 'Yogurt', 'A'),
('What is the primary flavoring agent in a traditional Caesar salad dressing?', 'Lemon', 'Garlic', 'Anchovies', 'Mustard', 'C'),
('Which fruit is used to make a classic "piña colada"?', 'Pineapple', 'Coconut', 'Mango', 'Strawberry', 'A'),
('What is the name of the Japanese dish consisting of raw fish served with rice and often wrapped in seaweed?', 'Sashimi', 'Sushi', 'Tempura', 'Teriyaki', 'B'),
('What type of chocolate is made from cocoa solids, cocoa butter, and sugar without any milk content?', 'Milk chocolate', 'White chocolate', 'Dark chocolate', 'Ruby chocolate', 'C'),
('Which type of nut is traditionally used in making marzipan?', 'Almond', 'Hazelnut', 'Cashew', 'Walnuts', 'A'),
('What alcoholic drink is typically used in a traditional "Mojito"?', 'Vodka', 'Tequila', 'Rum', 'Gin', 'C'),
('Which fruit is known for its high vitamin C content and is often associated with preventing scurvy?', 'Orange', 'Apple', 'Banana', 'Grapefruit', 'A'),
('Which of these dishes is traditionally made with mashed potatoes and gravy, often served with roast meat?', 'Shepherd''s pie', 'Tater tots', 'Poutine', 'Bangers and mash', 'D'),
('Which ingredient is key in making a traditional French "baguette"?', 'Sugar', 'Salt', 'Yeast', 'Butter', 'C'),
('Which type of bread is used to make the traditional Greek dish "souvlaki"?', 'Pita', 'Ciabatta', 'Baguette', 'Naan', 'A'),
('Which type of fruit is used to make "Cider"?', 'Apple', 'Pear', 'Grapes', 'Mango', 'A');


CREATE TABLE Travel (
    question_id INT AUTO_INCREMENT PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A', 'B', 'C', 'D') NOT NULL
);
INSERT INTO Travel (question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('What is the capital city of Japan?', 'Kyoto', 'Tokyo', 'Osaka', 'Hiroshima', 'B'),
('Which is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'B'),
('Which country is home to the Great Barrier Reef?', 'South Africa', 'Australia', 'Thailand', 'Fiji', 'B'),
('What is the tallest mountain in the world?', 'K2', 'Mount Everest', 'Mount Kilimanjaro', 'Mount Fuji', 'B'),
('Which country is famous for its ancient pyramids, including the Great Pyramid of Giza?', 'Mexico', 'Greece', 'Egypt', 'India', 'C'),
('What city is known as the "City of Love"?', 'New York', 'Paris', 'Venice', 'Barcelona', 'B'),
('Which country has the most pyramids in the world?', 'Egypt', 'Sudan', 'Mexico', 'Peru', 'B'),
('What is the currency of the United Kingdom?', 'Euro', 'Pound Sterling', 'Dollar', 'Franc', 'B'),
('Which island is known for its famous stone statues, called Moai?', 'Bali', 'Easter Island', 'Madagascar', 'Galapagos Islands', 'B'),
('Which U.S. national park is known for its geysers, including the famous Old Faithful?', 'Yosemite', 'Grand Canyon', 'Yellowstone', 'Zion', 'C'),
('Which city is home to the famous landmark, the Colosseum?', 'Athens', 'Rome', 'Cairo', 'Istanbul', 'B'),
('What is the name of the longest wall in the world, located in China?', 'Hadrian''s Wall', 'The Great Wall of China', 'Berlin Wall', 'Wall of Jericho', 'B'),
('Which island nation is known for its giant tortoises and unique wildlife, and is located in the Pacific Ocean?', 'Madagascar', 'Fiji', 'Seychelles', 'Galapagos Islands', 'D'),
('In which country can you visit the ancient city of Petra, a UNESCO World Heritage Site?', 'Egypt', 'Jordan', 'Israel', 'Lebanon', 'B'),
('Which natural wonder is found at the border of Zimbabwe and Zambia?', 'Niagara Falls', 'Victoria Falls', 'Angel Falls', 'Iguazu Falls', 'B'),
('Which desert is the largest in the world?', 'Atacama', 'Sahara', 'Gobi', 'Kalahari', 'B'),
('Which island is famous for its volcano, Mount Vesuvius, and the ancient Roman cities of Pompeii and Herculaneum?', 'Sicily', 'Capri', 'Sardinia', 'Ischia', 'A'),
('Which country is home to the famous Inca ruins of Machu Picchu?', 'Chile', 'Peru', 'Ecuador', 'Bolivia', 'B'),
('What is the name of the world-famous tower located in Paris, France?', 'Eiffel Tower', 'CN Tower', 'Leaning Tower of Pisa', 'Burj Khalifa', 'A'),
('Which island group is famous for its unique wildlife, including lemurs, and is located off the southeastern coast of Africa?', 'Madagascar', 'Maldives', 'Canary Islands', 'Azores', 'A'),
('Which country is home to the Great Wall and the Forbidden City?', 'South Korea', 'India', 'China', 'Japan', 'C'),
('Which U.S. state is known as "The Sunshine State"?', 'California', 'Florida', 'Hawaii', 'Texas', 'B'),
('Which popular travel destination is known for its iconic ancient structures, including the Parthenon?', 'Athens', 'Rome', 'Cairo', 'Istanbul', 'A'),
('Which city is home to the famous landmark, the Statue of Liberty?', 'Los Angeles', 'Washington D.C.', 'Chicago', 'New York City', 'D'),
('Which South American country is known for its tango music and dance?', 'Argentina', 'Brazil', 'Chile', 'Uruguay', 'A');